GET http://localhost:3003/api/blogs/


# POST http://localhost:3003/api/blogs
# Content-Type: application/json

# {
#    "title": "How I stopped worrying",
#   "author": "Sr StrangeLove",
#   "url": "https://www.drStrangeLove.com",
#   "likes": 1
# }
