# GET http://localhost:3003/api/blogs/


# POST http://localhost:3003/api/blogs
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0dGUiLCJpZCI6IjVmYjU3NWFiY2Y4OGM0M2JiYzkxNjRiZSIsImlhdCI6MTYwNTcyNzY2OH0.nIkpyGK5pl_uqpZsYfXz56P106hdPJ7eNuNUxetbNw8

# {
#   "title": "Uusi posti ",
#   "author": "Sr Senipr",
#   "url": "https://www.srProgress.com",
#   "likes": 115
# }




# PUT http://localhost:3003/api/blogs/5fa531efe59b206890d1a4b4
# Content-Type: application/json

# {
#   "likes": 1115
# }



DELETE http://localhost:3003/api/blogs/5fb57615cf88c43bbc9164bf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0dGUiLCJpZCI6IjVmYjU3NWFiY2Y4OGM0M2JiYzkxNjRiZSIsImlhdCI6MTYwNTcyNzY2OH0.nIkpyGK5pl_uqpZsYfXz56P106hdPJ7eNuNUxetbNw8


# Content-Type: application/json


# POST http://localhost:3003/api/login 
# Content-Type: application/json

# {
# "username": "atte",
# "password": "patte"
# }

# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
# "username": "atte",
# "name": "atte",
# "password": "patte"
# }
//GET http://localhost:3003/api/users/

