//GET http://localhost:3003/api/blogs/


# POST http://localhost:3003/api/blogs
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNzYWNzYSIsImlkIjoiNWZhNmRkMTIxODk5OTE3OWE0MzM2YWIxIiwiaWF0IjoxNjA0OTUxOTk3fQ.WxE-ZS3HILUXJ-fgIcyL9Ig_DBDhd8xXlwSPHpdTie0

# {
#   "title": "Uusi posti ",
#   "author": "Sr Senipr",
#   "url": "https://www.srProgress.com",
#   "likes": 115
# }




# PUT http://localhost:3003/api/blogs/5fa531efe59b206890d1a4b4
# Content-Type: application/json

# {
#   "likes": 1115
# }



# DELETE http://localhost:3003/api/blogs/5fa531efe59b206890d1a4b3
# Content-Type: application/json


# POST http://localhost:3003/api/login 
# Content-Type: application/json

# {
# "username": "atte",
# "password": "patte"
# }

# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
# "username": "atte",
# "name": "atte",
# "password": "patte"
# }
//GET http://localhost:3003/api/users/